### ISSUE TITLE
new website: follow up issues

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1329]
https://octokit.github.io/rest.js/

- [ ] whitespace on right of header bar for screens < 360px  (https://github.com/gr2m/octokit-rest-documentation/issues/42)
- [x] After click on menu, target heading is hidden behind header bar (https://github.com/gr2m/octokit-rest-documentation/issues/40)
- [ ] Update URL when scrolling between sections (https://github.com/gr2m/octokit-rest-documentation/issues/5)
- [ ] Make 3 column design (https://github.com/gr2m/octokit-rest-documentation/issues/20)

**Comment by janl** [comment]
doesn’t work in Safari/Mac:

```
[Error] ReferenceError: Can't find variable: IntersectionObserver
	da (app-84d26d92f63eeec6c7e1.js:1:134948)
	callback (app-84d26d92f63eeec6c7e1.js:1:140341)
	oa (app-84d26d92f63eeec6c7e1.js:1:132784)
	ra (app-84d26d92f63eeec6c7e1.js:1:132532)
	Ba (app-84d26d92f63eeec6c7e1.js:1:142546)
	Va (app-84d26d92f63eeec6c7e1.js:1:145020)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:158227)
	unstable_runWithPriority (app-84d26d92f63eeec6c7e1.js:1:168940)
	jl (app-84d26d92f63eeec6c7e1.js:1:158184)
	Ol (app-84d26d92f63eeec6c7e1.js:1:157938)
	Cl (app-84d26d92f63eeec6c7e1.js:1:157283)
	kl (app-84d26d92f63eeec6c7e1.js:1:156304)
	Ja (app-84d26d92f63eeec6c7e1.js:1:155178)
	Il (app-84d26d92f63eeec6c7e1.js:1:159193)
	render (app-84d26d92f63eeec6c7e1.js:1:163038)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:160897)
	Hl (app-84d26d92f63eeec6c7e1.js:1:160826)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:190760)
[Error] ReferenceError: Can't find variable: IntersectionObserver
	da (app-84d26d92f63eeec6c7e1.js:1:134948)
	callback (app-84d26d92f63eeec6c7e1.js:1:139995)
	oa (app-84d26d92f63eeec6c7e1.js:1:132784)
	ra (app-84d26d92f63eeec6c7e1.js:1:132532)
	Ba (app-84d26d92f63eeec6c7e1.js:1:142703)
	Va (app-84d26d92f63eeec6c7e1.js:1:145020)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:158227)
	unstable_runWithPriority (app-84d26d92f63eeec6c7e1.js:1:168940)
	jl (app-84d26d92f63eeec6c7e1.js:1:158184)
	Ol (app-84d26d92f63eeec6c7e1.js:1:157938)
	Cl (app-84d26d92f63eeec6c7e1.js:1:157283)
	kl (app-84d26d92f63eeec6c7e1.js:1:156304)
	Ja (app-84d26d92f63eeec6c7e1.js:1:155178)
	Il (app-84d26d92f63eeec6c7e1.js:1:159193)
	render (app-84d26d92f63eeec6c7e1.js:1:163038)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:160897)
	Hl (app-84d26d92f63eeec6c7e1.js:1:160826)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:190760)
[Error] ReferenceError: Can't find variable: IntersectionObserver
	Cl (app-84d26d92f63eeec6c7e1.js:1:157488)
	kl (app-84d26d92f63eeec6c7e1.js:1:156304)
	Ja (app-84d26d92f63eeec6c7e1.js:1:155178)
	Il (app-84d26d92f63eeec6c7e1.js:1:159193)
	render (app-84d26d92f63eeec6c7e1.js:1:163038)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:160897)
	Hl (app-84d26d92f63eeec6c7e1.js:1:160826)
	(anonymous function) (app-84d26d92f63eeec6c7e1.js:1:190760)
```

**Comment by gr2m** [comment]
What Safari version is that? It works for me without problems in Version 12.1 (14607.1.40.1.4). It looks like support was only added in the latest version of Safari for Mac/iOS: https://caniuse.com/#search=IntersectionObserver

I’ll see if we can fail gracefully for older browsers that don’t support `IntersectionObserver`. Thanks!

**Comment by gr2m** [comment]
> doesn’t work in Safari/Mac:

That should be resolved now, via 6827002

@janl can you confirm please?

**Comment by wolfy1339** [comment]
Can't this be polyfilled for older browsers? Instead of not rendering components

**Comment by gr2m** [comment]
It’s only used to highlight the current navigation item, it’s not necessary

**Comment by copperwall** [comment]
Hey @gr2m, I'm up to work on the uncompleted parts of this issue if they're still valid. It looks like the links for each of the checkboxes are dead though

**Comment by gr2m** [comment]
Hey thanks for offering to help out! 

https://github.com/gr2m/octokit-rest-documentation was just a temporary repository, I thought I migrated all open issues over, but looks like I didn't :( 

i've made a gif to show the problem with the white space:
![Kapture 2020-03-29 at 11 18 14](https://user-images.githubusercontent.com/39992/77856883-0d9f9880-71af-11ea-8c13-ddbd2a7604e7.gif)

There should be no horizontal scrolling. Would you like to look into this one?

**Comment by copperwall** [comment]
Yeah definitely! Sorry for the delay, I didn't see your response until now. I'd love to look into that.

**Comment by copperwall** [comment]
I made a PR at #1677 for the whitespace issue, but I didn't add a "Closes #" in the description because I wasn't sure if the other unchecked boxes are still valid to work on.

As always happy to make changes if there's any issues in the PR!

**Comment by gr2m** [comment]
I'd say it's good enough, thanks :) I'll make another issue about the search, it seems to have stopped working with the new version. Would you like to look into that?

**Comment by copperwall** [comment]
Yeah I’d love to!

**Comment by gr2m** [comment]
All yours :) https://github.com/octokit/rest.js/issues/1678
